site_name: Aware Technical Documentation
site_url: https://kallol-cognizant.github.io/mkdocs/
site_description: Aware Technical Documentation
site_author: Kallol Das

repo_url: https://github.com/kallol-cognizant/mkdocs

copyright: Copyright &copy; 2022 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.

theme:
    name: bootstrap

nav:
    - Home: index.md

plugins:
    - search
